package it.grupposnai.paymatservices.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import it.grupposnai.paymatservices.model.ObjectFactory;
import it.grupposnai.paymatservices.model.request.login.CheckPaymentLoginConfirmationRequest;
import it.grupposnai.paymatservices.model.request.login.PaymentLoginRequest;
import it.grupposnai.paymatservices.model.request.ricaricaConto.CancelRicaricaContoRequest;
import it.grupposnai.paymatservices.model.request.ricaricaConto.ConfirmRicaricaContoRequest;
import it.grupposnai.paymatservices.model.request.ricaricaConto.ReserveRicaricaContoRequest;
import it.grupposnai.paymatservices.model.request.ricaricaContoGioco.ConfirmRicaricaContoGiocoRequest;
import it.grupposnai.paymatservices.model.request.ricaricaContoGioco.ReserveRicaricaContoGiocoRequest;
import it.grupposnai.paymatservices.model.response.login.CheckPaymentLoginConfirmationResponse;
import it.grupposnai.paymatservices.model.response.login.PaymentLoginResponse;
import it.grupposnai.paymatservices.model.response.ricaricaConto.CancelRicaricaContoResponse;
import it.grupposnai.paymatservices.model.response.ricaricaConto.ConfirmRicaricaContoResponse;
import it.grupposnai.paymatservices.model.response.ricaricaConto.ReserveRicaricaContoResponse;
import it.grupposnai.paymatservices.model.response.ricaricaContoGioco.ConfirmRicaricaContoGiocoResponse;
import it.grupposnai.paymatservices.model.response.ricaricaContoGioco.ReserveRicaricaContoGiocoResponse;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-10-26T14:54:32.984+02:00
 * Generated source version: 3.1.8
 *
 */
@WebService(targetNamespace = "http://ws.paymatservizi.it/", name = "PaymatServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface PaymatServiceSoap {

    // Metodi autogenerati, ereditati dal wsdl della versione .net di PaymatServices

    /**
     * reserveRicaricaTelefonica
     */
    @WebMethod(action = "http://ws.paymatservizi.it/reserveRicaricaTelefonica")
    @RequestWrapper(localName = "reserveRicaricaTelefonica", targetNamespace = "http://ws.paymatservizi.it/", className = "it.grupposnai.paymatservices.model.request.ricarica.ReserveRicaricaTelefonica")
    @ResponseWrapper(localName = "reserveRicaricaTelefonicaResponse", targetNamespace = "http://ws.paymatservizi.it/", className = "it.grupposnai.paymatservices.model.response.ricarica.ReserveRicaricaTelefonicaResponse")
    @WebResult(name = "reserveRicaricaTelefonicaResult", targetNamespace = "http://ws.paymatservizi.it/")
    public it.grupposnai.paymatservices.model.response.ricarica.ReserveRicaricaTelefonicaResponse2 reserveRicaricaTelefonica(
            @WebParam(name = "request", targetNamespace = "http://ws.paymatservizi.it/")
            it.grupposnai.paymatservices.model.request.ricarica.ReserveRicaricaTelefonicaRequest request
    );

    /**
     * confirmRicaricaTelefonica
     */
    @WebMethod(action = "http://ws.paymatservizi.it/confirmRicaricaTelefonica")
    @RequestWrapper(localName = "confirmRicaricaTelefonica", targetNamespace = "http://ws.paymatservizi.it/", className = "it.grupposnai.paymatservices.model.request.ricarica.ConfirmRicaricaTelefonica")
    @ResponseWrapper(localName = "confirmRicaricaTelefonicaResponse", targetNamespace = "http://ws.paymatservizi.it/", className = "it.grupposnai.paymatservices.model.response.ricarica.ConfirmRicaricaTelefonicaResponse")
    @WebResult(name = "confirmRicaricaTelefonicaResult", targetNamespace = "http://ws.paymatservizi.it/")
    public it.grupposnai.paymatservices.model.response.ricarica.ConfirmRicaricaTelefonicaResponse2 confirmRicaricaTelefonica(
            @WebParam(name = "request", targetNamespace = "http://ws.paymatservizi.it/")
            it.grupposnai.paymatservices.model.request.ricarica.ConfirmRicaricaTelefonicaRequest request
    );

    /**
     * infoTagliRicariche
     */
    @WebMethod(action = "http://ws.paymatservizi.it/infoTagliRicariche")
    @RequestWrapper(localName = "infoTagliRicariche", targetNamespace = "http://ws.paymatservizi.it/", className = "it.grupposnai.paymatservices.model.request.ricarica.InfoTagliRicariche")
    @ResponseWrapper(localName = "infoTagliRicaricheResponse", targetNamespace = "http://ws.paymatservizi.it/", className = "it.grupposnai.paymatservices.model.response.ricarica.InfoTagliRicaricheResponse")
    @WebResult(name = "infoTagliRicaricheResult", targetNamespace = "http://ws.paymatservizi.it/")
    public it.grupposnai.paymatservices.model.response.ricarica.InfoTaglioRicaricheResponse infoTagliRicariche(
            @WebParam(name = "request", targetNamespace = "http://ws.paymatservizi.it/")
            it.grupposnai.paymatservices.model.request.ricarica.InfoTaglioRicaricheRequest request
    );

    /**
     * infoBrandRicariche
     */
    @WebMethod(action = "http://ws.paymatservizi.it/infoBrandRicariche")
    @RequestWrapper(localName = "infoBrandRicariche", targetNamespace = "http://ws.paymatservizi.it/", className = "it.grupposnai.paymatservices.model.request.ricarica.InfoBrandRicariche")
    @ResponseWrapper(localName = "infoBrandRicaricheResponse", targetNamespace = "http://ws.paymatservizi.it/", className = "it.grupposnai.paymatservices.model.response.ricarica.InfoBrandRicaricheResponse")
    @WebResult(name = "infoBrandRicaricheResult", targetNamespace = "http://ws.paymatservizi.it/")
    public it.grupposnai.paymatservices.model.response.ricarica.InfoBrandRicaricheResponse2 infoBrandRicariche(
            @WebParam(name = "request", targetNamespace = "http://ws.paymatservizi.it/")
            it.grupposnai.paymatservices.model.request.ricarica.InfoBrandRicaricheRequest request
    );

    /**
     * cancelRicaricaTelefonica
     */
    @WebMethod(action = "http://ws.paymatservizi.it/cancelRicaricaTelefonica")
    @RequestWrapper(localName = "cancelRicaricaTelefonica", targetNamespace = "http://ws.paymatservizi.it/", className = "it.grupposnai.paymatservices.model.request.ricarica.CancelRicaricaTelefonica")
    @ResponseWrapper(localName = "cancelRicaricaTelefonicaResponse", targetNamespace = "http://ws.paymatservizi.it/", className = "it.grupposnai.paymatservices.model.response.ricarica.CancelRicaricaTelefonicaResponse")
    @WebResult(name = "cancelRicaricaTelefonicaResult", targetNamespace = "http://ws.paymatservizi.it/")
    public it.grupposnai.paymatservices.model.response.ricarica.CancelRicaricaTelefonicaResponse2 cancelRicaricaTelefonica(
            @WebParam(name = "request", targetNamespace = "http://ws.paymatservizi.it/")
            it.grupposnai.paymatservices.model.request.ricarica.CancelRicaricaTelefonicaRequest request
    );

    // Nuovi metodi

    // GENERALI

    /**
     * getCategorie
     */
    @WebMethod(action = "http://ws.paymatservizi.it/getCategorie")
    public it.grupposnai.paymatservices.model.response.generali.GetCategorieResponse getCategorie(it.grupposnai.paymatservices.model.request.generali.GetCategorieRequest request);

    /**
     * getBrand
     */
    @WebMethod(action = "http://ws.paymatservizi.it/getBrand")
    public it.grupposnai.paymatservices.model.response.generali.GetBrandResponse getBrand(it.grupposnai.paymatservices.model.request.generali.GetBrandRequest request);

    /**
     * getTagli
     */
    @WebMethod(action = "http://ws.paymatservizi.it/getTagli")
    public it.grupposnai.paymatservices.model.response.generali.GetTagliResponse getTagli(it.grupposnai.paymatservices.model.request.generali.GetTagliRequest request);

    /**
     * getInfoTransazione
     */
    @WebMethod(action = "http://ws.paymatservizi.it/getInfoTransazione")
    public it.grupposnai.paymatservices.model.response.generali.InfoTransazioneResponse getInfoTransazione(it.grupposnai.paymatservices.model.request.generali.InfoTransazioneRequest response);

    /**
     * getInfoCreditoResiduo
     */
    @WebMethod(action = "http://ws.paymatservizi.it/getInfoCreditoResiduo")
    public it.grupposnai.paymatservices.model.response.generali.InfoCreditoResiduoResponse getInfoCreditoResiduo(it.grupposnai.paymatservices.model.request.generali.InfoCreditoResiduoRequest response);

    /**
     * getInfoCommissioni
     */
    @WebMethod(action = "http://ws.paymatservizi.it/getInfoCommissioni")
    public it.grupposnai.paymatservices.model.response.generali.InfoCommissioniResponse getInfoCommissioni(it.grupposnai.paymatservices.model.request.generali.InfoCommissioniRequest request);

    // PIN

    /**
     * infoBrandPin
     */
    @WebMethod(action = "http://ws.paymatservizi.it/infoBrandPin")
    public it.grupposnai.paymatservices.model.response.pin.InfoBrandPinResponse infoBrandPin(it.grupposnai.paymatservices.model.request.pin.InfoBrandPinRequest request);

    /**
     * infoTagliPin
     */
    @WebMethod(action = "http://ws.paymatservizi.it/infoTagliPin")
    public it.grupposnai.paymatservices.model.response.pin.InfoTagliPinResponse infoTagliPin(it.grupposnai.paymatservices.model.request.pin.InfoTagliPinRequest request);

    /**
     * reserveAcquistoPin
     */
    @WebMethod(action = "http://ws.paymatservizi.it/reserveAcquistoPin")
    public it.grupposnai.paymatservices.model.response.pin.ReserveAcquistoPinResponse reserveAcquistoPin(it.grupposnai.paymatservices.model.request.pin.ReserveAcquistoPinRequest request);

    /**
     * confirmAcquistoPin
     */
    @WebMethod(action = "http://ws.paymatservizi.it/confirmAcquistoPin")
    public it.grupposnai.paymatservices.model.response.pin.ConfirmAcquistoPinResponse confirmAcquistoPin(it.grupposnai.paymatservices.model.request.pin.ConfirmAcquistoPinRequest request);

    /**
     * cancelAcquistoPin
     */
    @WebMethod(action = "http://ws.paymatservizi.it/cancelAcquistoPin")
    public it.grupposnai.paymatservices.model.response.pin.CancelAcquistoPinResponse cancelAcquistoPin(it.grupposnai.paymatservices.model.request.pin.CancelAcquistoPinRequest request);

    /**
     * reserveUsePin 
     */
    @WebMethod(action = "http://ws.paymatservizi.it/reserveUsePin")
    public it.grupposnai.paymatservices.model.response.pin.ReserveUsePinResponse reserveUsePin(it.grupposnai.paymatservices.model.request.pin.ReserveUsePinRequest request);

    /**
     * confirmUsoPin
     */
    @WebMethod(action = "http://ws.paymatservizi.it/confirmUsePin")
    public it.grupposnai.paymatservices.model.response.pin.ConfirmUsePinResponse confirmUsePin(it.grupposnai.paymatservices.model.request.pin.ConfirmUsePinRequest request);

    /**
     * cancelUsoPin
     */
    @WebMethod(action = "http://ws.paymatservizi.it/cancelUsePin")
    public it.grupposnai.paymatservices.model.response.pin.CancelUsePinResponse cancelUsePin(it.grupposnai.paymatservices.model.request.pin.CancelUsePinRequest request);

//    /**
//     * stornoAcquistoPin
//     */
//    @WebMethod(action = "http://ws.paymatservizi.it/stornoAcquistoPin")
//    public it.grupposnai.paymatservices.model.response.pin.StornoAcquistoPinResponse stornoAcquistoPin(it.grupposnai.paymatservices.model.request.pin.StornoAcquistoPinRequest request);

    // MAV/RAV

    /**
     * reserveMavRav
     */
    @WebMethod(action = "http://ws.paymatservizi.it/reserveMavRav")
    public it.grupposnai.paymatservices.model.response.prodottiFinanziari.mavRav.ReserveMavRavResponse reserveMavRav(it.grupposnai.paymatservices.model.request.prodottiFinanziari.mavRav.ReserveMavRavRequest request);

    /**
     * confirmMavRav
     */
    @WebMethod(action = "http://ws.paymatservizi.it/confirmMavRav")
    public it.grupposnai.paymatservices.model.response.prodottiFinanziari.mavRav.ConfirmMavRavResponse confirmMavRav(it.grupposnai.paymatservices.model.request.prodottiFinanziari.mavRav.ConfirmMavRavRequest request);

    /**
     * cancelMavRav
     */
    @WebMethod(action = "http://ws.paymatservizi.it/cancelMavRav")
    public it.grupposnai.paymatservices.model.response.prodottiFinanziari.mavRav.CancelMavRavResponse cancelMavRav(it.grupposnai.paymatservices.model.request.prodottiFinanziari.mavRav.CancelMavRavRequest request);

    // CBILL

    /**
     * reserveCbill
     */
    @WebMethod(action = "http://ws.paymatservizi.it/reserveCbill")
    public it.grupposnai.paymatservices.model.response.prodottiFinanziari.cbill.ReserveCbillResponse reserveCbill(it.grupposnai.paymatservices.model.request.prodottiFinanziari.cbill.ReserveCbillRequest request);

    /**
     * confirmCbill
     */
    @WebMethod(action = "http://ws.paymatservizi.it/confirmCbill")
    public it.grupposnai.paymatservices.model.response.prodottiFinanziari.cbill.ConfirmCbillResponse confirmCbill(it.grupposnai.paymatservices.model.request.prodottiFinanziari.cbill.ConfirmCbillRequest request);

    /**
     * cancelCbill
     */
    @WebMethod(action = "http://ws.paymatservizi.it/cancelCbill")
    public it.grupposnai.paymatservices.model.response.prodottiFinanziari.cbill.CancelCbillResponse cancelCbill(it.grupposnai.paymatservices.model.request.prodottiFinanziari.cbill.CancelCbillRequest request);

    /**
     * infoCbillGetBillers
     */
    @WebMethod(action = "http://ws.paymatservizi.it/infoCbillGetBillers")
    public it.grupposnai.paymatservices.model.response.prodottiFinanziari.cbill.InfoCbillGetBillersResponse infoCbillGetBillers(it.grupposnai.paymatservices.model.request.prodottiFinanziari.cbill.InfoCbillGetBillersRequest request);

    /**
     * infoCbillGetBills
     */
    @WebMethod(action = "http://ws.paymatservizi.it/infoCbillGetBills")
    public it.grupposnai.paymatservices.model.response.prodottiFinanziari.cbill.InfoCbillGetBillsResponse infoCbillGetBills(it.grupposnai.paymatservices.model.request.prodottiFinanziari.cbill.InfoCbillGetBillsRequest request);

    // Poste Pay

    /**
     * reservePostePay 
     */
    @WebMethod(action = "http://ws.paymatservizi.it/reservePostePay")
    public it.grupposnai.paymatservices.model.response.prodottiFinanziari.postePay.ReservePostePayResponse reservePostePay(it.grupposnai.paymatservices.model.request.prodottiFinanziari.postePay.ReservePostePayRequest request);

    /**
     * confirmPostePay 
     */
    @WebMethod(action = "http://ws.paymatservizi.it/confirmPostePay")
    public it.grupposnai.paymatservices.model.response.prodottiFinanziari.postePay.ConfirmPostePayResponse confirmPostePay(it.grupposnai.paymatservices.model.request.prodottiFinanziari.postePay.ConfirmPostePayRequest request);

    /**
     * cancelPostePay
     */
    @WebMethod(action = "http://ws.paymatservizi.it/cancelPostePay")
    public it.grupposnai.paymatservices.model.response.prodottiFinanziari.postePay.CancelPostePayResponse cancelPostePay(it.grupposnai.paymatservices.model.request.prodottiFinanziari.postePay.CancelPostePayRequest request);

    // Bollettini

    /**
     * reserveBollettino 
     */
    @WebMethod(action = "http://ws.paymatservizi.it/reserveBollettino")
    public it.grupposnai.paymatservices.model.response.prodottiFinanziari.bollettino.ReserveBollettinoResponse reserveBollettino(it.grupposnai.paymatservices.model.request.prodottiFinanziari.bollettino.ReserveBollettinoRequest request);

    /**
     * confirmBollettino 
     */
    @WebMethod(action = "http://ws.paymatservizi.it/confirmBollettino")
    public it.grupposnai.paymatservices.model.response.prodottiFinanziari.bollettino.ConfirmBollettinoResponse confirmBollettino(it.grupposnai.paymatservices.model.request.prodottiFinanziari.bollettino.ConfirmBollettinoRequest request);

    /**
     * cancelBollettino 
     */
    @WebMethod(action = "http://ws.paymatservizi.it/cancelBollettino")
    public it.grupposnai.paymatservices.model.response.prodottiFinanziari.bollettino.CancelBollettinoResponse cancelBollettino(it.grupposnai.paymatservices.model.request.prodottiFinanziari.bollettino.CancelBollettinoRequest request);

    /**
     * infoEnteBollettino
     */
    @WebMethod(action = "http://ws.paymatservizi.it/infoEnteBollettino")
    public it.grupposnai.paymatservices.model.response.prodottiFinanziari.bollettino.InfoEnteBollettinoResponse infoEnteBollettino(it.grupposnai.paymatservices.model.request.prodottiFinanziari.bollettino.InfoEnteBollettinoRequest request);

    /**
     * registrazioneEnteBollettino
     */
    @WebMethod(action = "http://ws.paymatservizi.it/registrazioneEnteBollettino")
    public it.grupposnai.paymatservices.model.response.prodottiFinanziari.bollettino.RegistrazioneEnteBollettinoResponse registrazioneEnteBollettino(it.grupposnai.paymatservices.model.request.prodottiFinanziari.bollettino.RegistrazioneEnteBollettinoRequest request);

    // Pago PA

    /**
     * reservePagoPa
     */
    @WebMethod(action = "http://ws.paymatservizi.it/reservePagoPa")
    public it.grupposnai.paymatservices.model.response.prodottiFinanziari.pagoPa.ReservePagoPaResponse reservePagoPa(it.grupposnai.paymatservices.model.request.prodottiFinanziari.pagoPa.ReservePagoPaRequest request);

    /**
     * confirmPagoPa    
     */
    @WebMethod(action = "http://ws.paymatservizi.it/confirmPagoPa")
    public it.grupposnai.paymatservices.model.response.prodottiFinanziari.pagoPa.ConfirmPagoPaResponse confirmPagoPa(it.grupposnai.paymatservices.model.request.prodottiFinanziari.pagoPa.ConfirmPagoPaRequest request);

    /**
     * cancelPagoPa
     */
    @WebMethod(action = "http://ws.paymatservizi.it/cancelPagoPa")
    public it.grupposnai.paymatservices.model.response.prodottiFinanziari.pagoPa.CancelPagoPaResponse cancelPagoPa(it.grupposnai.paymatservices.model.request.prodottiFinanziari.pagoPa.CancelPagoPaRequest request);

    // Bollo Auto

    /**
     * reserveBolloAuto
     */
    @WebMethod(action = "http://ws.paymatservizi.it/reserveBolloAuto")
    public it.grupposnai.paymatservices.model.response.prodottiFinanziari.bolloAuto.ReserveBolloAutoResponse reserveBolloAuto(it.grupposnai.paymatservices.model.request.prodottiFinanziari.bolloAuto.ReserveBolloAutoRequest request);

    /**
     * confirmBolloAuto    
     */
    @WebMethod(action = "http://ws.paymatservizi.it/confirmBolloAuto")
    public it.grupposnai.paymatservices.model.response.prodottiFinanziari.bolloAuto.ConfirmBolloAutoResponse confirmBolloAuto(it.grupposnai.paymatservices.model.request.prodottiFinanziari.bolloAuto.ConfirmBolloAutoRequest request);

    /**
     * cancelBolloAuto
     */
    @WebMethod(action = "http://ws.paymatservizi.it/cancelBolloAuto")
    public it.grupposnai.paymatservices.model.response.prodottiFinanziari.bolloAuto.CancelBolloAutoResponse cancelBolloAuto(it.grupposnai.paymatservices.model.request.prodottiFinanziari.bolloAuto.CancelBolloAutoRequest request);

    // SIM

    /**
     * reserveAcquistoSim
     */
    @WebMethod(action = "http://ws.paymatservizi.it/reserveAcquistoSim")
    public it.grupposnai.paymatservices.model.response.sim.ReserveAcquistoSimResponse reserveAcquistoSim(it.grupposnai.paymatservices.model.request.sim.ReserveAcquistoSimRequest request);

    /**
     * confirmAcquistoSim
     */
    @WebMethod(action = "http://ws.paymatservizi.it/confirmAcquistoSim")
    public it.grupposnai.paymatservices.model.response.sim.ConfirmAcquistoSimResponse confirmAcquistoSim(it.grupposnai.paymatservices.model.request.sim.ConfirmAcquistoSimRequest request);

    /**
     * cancelAcquistoSim
     */
    @WebMethod(action = "http://ws.paymatservizi.it/cancelAcquistoSim")
    public it.grupposnai.paymatservices.model.response.sim.CancelAcquistoSimResponse cancelAcquistoSim(it.grupposnai.paymatservices.model.request.sim.CancelAcquistoSimRequest request);

    /**
     * attivaLottoSim    
     */
    @WebMethod(action = "http://ws.paymatservizi.it/attivaLottoSim")
    public it.grupposnai.paymatservices.model.response.sim.AttivaLottoSimResponse attivaLottoSim(it.grupposnai.paymatservices.model.request.sim.AttivaLottoSimRequest request);

    /**
     * getDatiVoucherContoGioco
     */
    @WebMethod(action = "http://ws.paymatservizi.it/getDatiVoucherContoGioco")
    public it.grupposnai.paymatservices.model.response.snai.voucher.GetDatiVoucherContoGiocoResponse getDatiVoucherContoGioco(it.grupposnai.paymatservices.model.request.snai.voucher.GetDatiVoucherContoGiocoRequest request);

    /**
     * pagamentoVoucherContoGioco
     */
    @WebMethod(action = "http://ws.paymatservizi.it/pagamentoVoucherContoGioco")
    public it.grupposnai.paymatservices.model.response.snai.voucher.PagamentoVoucherContoGiocoResponse pagamentoVoucherContoGioco(it.grupposnai.paymatservices.model.request.snai.voucher.PagamentoVoucherContoGiocoRequest request);

    /**
     * getPrelieviContoGioco
     */
    @WebMethod(action = "http://ws.paymatservizi.it/getPrelieviContoGioco")
    public it.grupposnai.paymatservices.model.response.snai.voucher.GetPrelieviContoGiocoResponse getPrelieviContoGioco(it.grupposnai.paymatservices.model.request.snai.voucher.GetPrelieviContoGiocoRequest request);

    // Payment Code

//    /**
//     * reservePaymentCode
//     */
//    @WebMethod(action = "http://ws.paymatservizi.it/reservePaymentCode")
//    public it.grupposnai.paymatservices.model.response.prodottiFinanziari.paymentCode.ReservePaymentCodeResponse reservePaymentCode(it.grupposnai.paymatservices.model.request.prodottiFinanziari.paymentCode.ReservePaymentCodeRequest request);
//    
//    /**
//     * confirmPaymentCode
//     */
//    @WebMethod(action = "http://ws.paymatservizi.it/confirmPaymentCode")
//    public it.grupposnai.paymatservices.model.response.prodottiFinanziari.paymentCode.ConfirmPaymentCodeResponse confirmPaymentCode(it.grupposnai.paymatservices.model.request.prodottiFinanziari.paymentCode.ConfirmPaymentCodeRequest request);
//    
//    /**
//     * cancelPaymentCode
//     */
//    @WebMethod(action = "http://ws.paymatservizi.it/cancelPaymentCode")
//    public it.grupposnai.paymatservices.model.response.prodottiFinanziari.paymentCode.CancelPaymentCodeResponse cancelPaymentCode(it.grupposnai.paymatservices.model.request.prodottiFinanziari.paymentCode.CancelPaymentCodeRequest request);

    // BollettinoFreccia

    /**
     * reserveBollettinoFreccia 
     */
    @WebMethod(action = "http://ws.paymatservizi.it/reserveBollettinoFreccia")
    public it.grupposnai.paymatservices.model.response.prodottiFinanziari.bollettinoFreccia.ReserveBollettinoFrecciaResponse reserveBollettinoFreccia(it.grupposnai.paymatservices.model.request.prodottiFinanziari.bollettinoFreccia.ReserveBollettinoFrecciaRequest request);

    /**
     * confirmBollettinoFreccia
     */
    @WebMethod(action = "http://ws.paymatservizi.it/confirmBollettinoFreccia")
    public it.grupposnai.paymatservices.model.response.prodottiFinanziari.bollettinoFreccia.ConfirmBollettinoFrecciaResponse confirmBollettinoFreccia(it.grupposnai.paymatservices.model.request.prodottiFinanziari.bollettinoFreccia.ConfirmBollettinoFrecciaRequest request);

    /**
     * cancelBollettinoFreccia
     */
    @WebMethod(action = "http://ws.paymatservizi.it/cancelBollettinoFreccia")
    public it.grupposnai.paymatservices.model.response.prodottiFinanziari.bollettinoFreccia.CancelBollettinoFrecciaResponse cancelBollettinoFreccia(it.grupposnai.paymatservices.model.request.prodottiFinanziari.bollettinoFreccia.CancelBollettinoFrecciaRequest request);


    /*
     * reserveRicaricaConto
     */
    @WebMethod(action = "http://ws.paymatservizi.it/reserveRicaricaConto")
    public ReserveRicaricaContoResponse reserveRicaricaConto(ReserveRicaricaContoRequest request);

    /*
     * confirmRicaricaConto
     */
    @WebMethod(action = "http://ws.paymatservizi.it/confirmRicaricaConto")
    public ConfirmRicaricaContoResponse confirmRicaricaConto(ConfirmRicaricaContoRequest request);

    /*
     * cancelRicaricaConto
     */
    @WebMethod(action = "http://ws.paymatservizi.it/cancelRicaricaConto")
    public CancelRicaricaContoResponse cancelRicaricaConto(CancelRicaricaContoRequest request);


    @WebMethod(action = "http://ws.paymatservizi.it/paymentLogin")
    public PaymentLoginResponse paymentLogin(PaymentLoginRequest request);

    @WebMethod(action = "http://ws.paymatservizi.it/checkPaymentLoginConfirmation")
    public CheckPaymentLoginConfirmationResponse checkPaymentLoginConfirmation(CheckPaymentLoginConfirmationRequest request);

    /**
     * cancelAcquistoPinVivacard
     */
    @WebMethod(action = "http://ws.paymatservizi.it/cancelAcquistoPinVivacard")
    public it.grupposnai.paymatservices.model.response.pin.CancelAcquistoPinVivacardResponse cancelAcquistoPinVivacard(it.grupposnai.paymatservices.model.request.pin.CancelAcquistoPinVivacardRequest request);

    /**
     * ReserveRicaricaContoGioco
     * questo endpoint permette di ricaricare il conto gioco.
     * Se il totale settimanale di ricariche supera i 100€ passeremo per Aircash, altrimenti andremo direttamente a ricaricare il conto gioco
     */
    @WebMethod(action = "http://ws.paymatservizi.it/reserveRicaricaContoGioco")
    public ReserveRicaricaContoGiocoResponse reserveRicaricaContoGioco(ReserveRicaricaContoGiocoRequest request);

    /**
     * ConfirmRicaricaContoGioco
     * questo endpoint permette di ricaricare il conto gioco.
     * Se il totale settimanale di ricariche supera i 100€ passeremo per Aircash, altrimenti andremo direttamente a ricaricare il conto gioco
     */
    @WebMethod(action = "http://ws.paymatservizi.it/confirmRicaricaContoGioco")
    public ConfirmRicaricaContoGiocoResponse confirmRicaricaContoGioco(ConfirmRicaricaContoGiocoRequest request);

}
