package it.grupposnai.paymatservices.services;

import com.fasterxml.jackson.databind.ObjectMapper;
import it.cogetech.lib.common.util.Configurazione;
import it.cogetech.lib.common.util.IpAddress;
import it.cogetech.lib.common.util.XmlSerializer;
import it.cogetech.lib.db.util.CostantiDB;
import it.grupposnai.paymatcore.api.PaymatCoreApi;
import it.grupposnai.paymatservices.AuditLogDelegate;
import it.grupposnai.paymatservices.adapter.*;
import it.grupposnai.paymatservices.kafka.KafkaInterceptor;
import it.grupposnai.paymatservices.model.request.generali.*;
import it.grupposnai.paymatservices.model.request.pin.*;
import it.grupposnai.paymatservices.model.request.prodottiFinanziari.bollettino.*;
import it.grupposnai.paymatservices.model.request.prodottiFinanziari.cbill.*;
import it.grupposnai.paymatservices.model.request.ricarica.*;
import it.grupposnai.paymatservices.model.response.generali.*;
import it.grupposnai.paymatservices.model.response.pin.*;
import it.grupposnai.paymatservices.model.response.prodottiFinanziari.bollettino.*;
import it.grupposnai.paymatservices.model.response.prodottiFinanziari.cbill.*;
import it.grupposnai.paymatservices.model.response.ricarica.*;
import it.grupposnai.paymatservices.util.CostantiWsPaymat;
import org.apache.log4j.Logger;

import javax.annotation.Resource;
import javax.interceptor.Interceptors;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.servlet.http.HttpServletRequest;
import javax.xml.ws.BindingType;
import javax.xml.ws.WebServiceContext;
import javax.xml.ws.handler.MessageContext;
import java.io.File;
import java.io.IOException;
import java.util.Map;


/**
 * This class was generated by Apache CXF 3.1.8 2016-10-26T14:54:32.927+02:00
 * Generated source version: 3.1.8
 */
@Interceptors(KafkaInterceptor.class)
@javax.jws.WebService(targetNamespace = "http://ws.paymatservizi.it/")
@BindingType(value = "http://www.w3.org/2003/05/soap/bindings/HTTP/")
public class PaymatServiceSoap12Impl implements PaymatServiceSoap {

    @Resource
    WebServiceContext context;
    private static final Logger LOG = Logger.getLogger(PaymatServiceSoap12Impl.class.getName());
    private PaymatCoreApi paymatCoreApi;
    private static final Integer ID_BRAND_FASTWEB = 1;









    public InfoTransazioneResponse getInfoTransazione(InfoTransazioneRequest request) {
        LOG.info("Request: " + request);
        InfoTransazioneResponse response;
        try {
            it.grupposnai.paymatcore.api.request.info.InfoTransazioneRequest coreRequest = GeneraliAdapter.getInfoTransazioneRequest(request);
            it.grupposnai.paymatcore.api.response.info.InfoTransazioneResponse coreResponse = getPaymatCoreApi().getInfoTransazione(coreRequest);
            response = GeneraliAdapter.getInfoTransazioniResponse(coreResponse);
        } catch (Exception ex) {
            // ERRORE IMPREVISTO
            LOG.error("Errore imprevisto", ex);
            response = new InfoTransazioneResponse();
            response.setResultCode(-101);
            response.setResultDesc("Errore imprevisto " + ex.getMessage());
        }
        response.setCallerId(request.getCallerId());
        response.setRequestId(request.getRequestId());
        LOG.info("Response: " + response);
        return response;
    }



    public ReserveRicaricaTelefonicaResponse2 reserveRicaricaTelefonica(ReserveRicaricaTelefonicaRequest request) {

        ReserveRicaricaTelefonicaResponse2 response = new  ReserveRicaricaTelefonicaResponse2();
        response.setCallerId(request.getCallerId());
        response.setRequestId(request.getRequestId());

//        if (request.validate() != null) {
//            LOG.info("Request: " + request);
//            response.setResultCode("1");
//            response.setResultDesc(CostantiWsPaymat.VALIDATION_ERROR_DESC + ":" + request.validate());
//            LOG.info("Response: " + response);
//            return response;
//        }

        ObjectMapper mapper = new ObjectMapper();
        String pathMockResponse = Configurazione.INSTANCE.getString(CostantiWsPaymat.MOCK_RESPONSE_RESERVE);
        String absolutPath = pathMockResponse + request.getBrand() + ".json";

        File file = new File(absolutPath);

        if (file.exists()) {

            try {
                response = mapper.readValue(file,ReserveRicaricaTelefonicaResponse2.class);
            } catch (IOException e) {
                response.setResultCode("100");
                response.setResultDesc("Errore nel recupero dei dati da file " + e.getMessage());
            }

        }else{
            response.setResultCode("100");
            response.setResultDesc("File contenente le informazioni mancante.");
        }

    return response;

    }


    public ConfirmRicaricaTelefonicaResponse2 confirmRicaricaTelefonica(ConfirmRicaricaTelefonicaRequest request) {
        ConfirmRicaricaTelefonicaResponse2 response = new ConfirmRicaricaTelefonicaResponse2();
        response.setCallerId(request.getCallerId());
        response.setRequestId(request.getRequestId());

//        if (request.validate() != null) {
//            LOG.info("Request: " + request);
//            response.setResultCode("1");
//            response.setResultDesc(CostantiWsPaymat.VALIDATION_ERROR_DESC + ":" + request.validate());
//            LOG.info("Response: " + response);
//            return response;
//        }

        ObjectMapper mapper = new ObjectMapper();
        String pathMockResponse = Configurazione.INSTANCE.getString(CostantiWsPaymat.MOCK_RESPONSE_CONFIRM);
        String absolutPath = pathMockResponse + request.getBrand() + ".json";

        File file = new File(absolutPath);

        if (file.exists()) {
            try {
                response = mapper.readValue(file,ConfirmRicaricaTelefonicaResponse2.class);
            } catch (Exception e) {
                response.setResultCode("100");
                response.setResultDesc("Errore nel recupero dei dati da file " + e.getMessage());
            }

        }else{
            response.setResultCode("100");
            response.setResultDesc("File contenente le informazioni mancante.");
        }

        return response;

    }


    public CancelRicaricaTelefonicaResponse2 cancelRicaricaTelefonica(CancelRicaricaTelefonicaRequest request) {

        CancelRicaricaTelefonicaResponse2 response = new CancelRicaricaTelefonicaResponse2();
        response.setCallerId(request.getCallerId());
        response.setRequestId(request.getRequestId());

//        if (request.validate() != null) {
//            LOG.info("Request: " + request);
//            response.setResultCode("1");
//            response.setResultDesc(CostantiWsPaymat.VALIDATION_ERROR_DESC + ":" + request.validate());
//            LOG.info("Response: " + response);
//            return response;
//        }

        ObjectMapper mapper = new ObjectMapper();
        String pathMockResponse = Configurazione.INSTANCE.getString(CostantiWsPaymat.MOCK_RESPONSE_CANCEL);

        File file = new File(pathMockResponse);

        if (file.exists()) {
            try {
                response = mapper.readValue(file,CancelRicaricaTelefonicaResponse2.class);
            } catch (IOException e) {
                response.setResultCode("100");
                response.setResultDesc("Errore nel recupero dei dati da file " + e.getMessage());
            }

        }else{
            response.setResultCode("100");
            response.setResultDesc("File contenente le informazioni mancante.");
        }

        return response;

    }




    private PaymatCoreApi getPaymatCoreApi() throws NamingException {
        if (this.paymatCoreApi == null) {
            try {
                this.paymatCoreApi = new PaymatCoreApi(true, new InitialContext());
            } catch (NamingException e) {
                LOG.error("Errore nella creazione di PaymatCoreApi", e);
                throw e;
            }
        }
        return this.paymatCoreApi;
    }





}
