package it.grupposnai.paymatservices.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import it.grupposnai.paymatservices.model.ObjectFactory;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-10-26T14:54:32.984+02:00
 * Generated source version: 3.1.8
 *
 */
@WebService(targetNamespace = "http://ws.paymatservizi.it/", name = "PaymatServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface PaymatServiceSoap {

    // Metodi autogenerati, ereditati dal wsdl della versione .net di PaymatServices

    /**
     * reserveRicaricaTelefonica
     */
    @WebMethod(action = "http://ws.paymatservizi.it/reserveRicaricaTelefonica")
    @RequestWrapper(localName = "reserveRicaricaTelefonica", targetNamespace = "http://ws.paymatservizi.it/", className = "it.grupposnai.paymatservices.model.request.ricarica.ReserveRicaricaTelefonica")
    @ResponseWrapper(localName = "reserveRicaricaTelefonicaResponse", targetNamespace = "http://ws.paymatservizi.it/", className = "it.grupposnai.paymatservices.model.response.ricarica.ReserveRicaricaTelefonicaResponse")
    @WebResult(name = "reserveRicaricaTelefonicaResult", targetNamespace = "http://ws.paymatservizi.it/")
    public it.grupposnai.paymatservices.model.response.ricarica.ReserveRicaricaTelefonicaResponse2 reserveRicaricaTelefonica(
            @WebParam(name = "request", targetNamespace = "http://ws.paymatservizi.it/")
            it.grupposnai.paymatservices.model.request.ricarica.ReserveRicaricaTelefonicaRequest request
    );

    /**
     * confirmRicaricaTelefonica
     */
    @WebMethod(action = "http://ws.paymatservizi.it/confirmRicaricaTelefonica")
    @RequestWrapper(localName = "confirmRicaricaTelefonica", targetNamespace = "http://ws.paymatservizi.it/", className = "it.grupposnai.paymatservices.model.request.ricarica.ConfirmRicaricaTelefonica")
    @ResponseWrapper(localName = "confirmRicaricaTelefonicaResponse", targetNamespace = "http://ws.paymatservizi.it/", className = "it.grupposnai.paymatservices.model.response.ricarica.ConfirmRicaricaTelefonicaResponse")
    @WebResult(name = "confirmRicaricaTelefonicaResult", targetNamespace = "http://ws.paymatservizi.it/")
    public it.grupposnai.paymatservices.model.response.ricarica.ConfirmRicaricaTelefonicaResponse2 confirmRicaricaTelefonica(
            @WebParam(name = "request", targetNamespace = "http://ws.paymatservizi.it/")
            it.grupposnai.paymatservices.model.request.ricarica.ConfirmRicaricaTelefonicaRequest request
    );


    /**
     * cancelRicaricaTelefonica
     */
    @WebMethod(action = "http://ws.paymatservizi.it/cancelRicaricaTelefonica")
    @RequestWrapper(localName = "cancelRicaricaTelefonica", targetNamespace = "http://ws.paymatservizi.it/", className = "it.grupposnai.paymatservices.model.request.ricarica.CancelRicaricaTelefonica")
    @ResponseWrapper(localName = "cancelRicaricaTelefonicaResponse", targetNamespace = "http://ws.paymatservizi.it/", className = "it.grupposnai.paymatservices.model.response.ricarica.CancelRicaricaTelefonicaResponse")
    @WebResult(name = "cancelRicaricaTelefonicaResult", targetNamespace = "http://ws.paymatservizi.it/")
    public it.grupposnai.paymatservices.model.response.ricarica.CancelRicaricaTelefonicaResponse2 cancelRicaricaTelefonica(
            @WebParam(name = "request", targetNamespace = "http://ws.paymatservizi.it/")
            it.grupposnai.paymatservices.model.request.ricarica.CancelRicaricaTelefonicaRequest request
    );

}
